
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

const faqs = [
    {
        question: "What is Trader Choice?",
        answer: "Trader Choice is a platform that provides high-quality forex trading signals, market analysis, and educational content to help traders of all levels make more informed decisions."
    },
    {
        question: "How are the signals generated?",
        answer: "Our signals are generated by a combination of experienced professional traders and sophisticated, proprietary algorithms that analyze the market 24/7 for high-probability trading opportunities."
    },
    {
        question: "Is this platform suitable for beginners?",
        answer: "Absolutely. We provide clear entry, stop-loss, and take-profit points for every signal. Our platform is designed to be user-friendly, and our educational resources can help beginners learn the ropes."
    },
    {
        question: "What's the difference between the Free and Pro plans?",
        answer: "The Free plan provides access to two signals per day, giving you a taste of our service. The Pro plan unlocks unlimited signals, advanced analytics, premium content, and access to our exclusive trader community."
    },
    {
        question: "How do I upgrade to a Pro account?",
        answer: "Simply navigate to the Pricing page, choose the Pro plan, and follow the on-screen instructions. Once you're a member, you'll get instant access to all premium features."
    },
]

export function Faq() {
  return (
    <section className="bg-card py-20 md:py-32">
      <div className="container mx-auto px-4 md:px-6">
        <div className="text-center mb-12">
            <h2 className="font-headline text-4xl md:text-5xl font-bold">Frequently Asked Questions</h2>
            <p className="text-muted-foreground mt-3 max-w-2xl mx-auto">
                Have questions? We've got answers. Here are some of the most common queries we receive.
            </p>
        </div>

        <div className="max-w-3xl mx-auto">
            <Accordion type="single" collapsible className="w-full">
              {faqs.map((faq, index) => (
                 <AccordionItem key={index} value={`item-${index}`}>
                    <AccordionTrigger className="text-left font-headline text-lg">{faq.question}</AccordionTrigger>
                    <AccordionContent className="text-muted-foreground">
                        {faq.answer}
                    </AccordionContent>
                </AccordionItem>
              ))}
            </Accordion>
        </div>

      </div>
    </section>
  )
}
